# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
#pretty
permalink:           /:title 
#relative_permalinks: true

# Setup
title:               suninf
tagline:             'homepage'
header_title:        "Enjoy From Programming And Technique"
description:         'Creative thinking、Happy sharing！ If not now, when? If not you, who?'
baseurl:             http://www.suninf.net/
paginate:            5
paginate_path:       'page/:num'


