# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
#pretty
permalink:           /:title 
#relative_permalinks: true

# Setup
title:               suninf
tagline:             'homepage'
header_title:        "suninf 's blog"
header_description:  "Enjoy From Programming And Technique - "
header_url:          "suninf.net"
description:         'Creative thinking、Happy sharing！ If not now, when? If not you, who?'
url:                 http://www.suninf.net
baseurl:             /
index_url:           /index.html
paginate:            5
paginate_path:       'page/:num'


